name: Sync to Hugging Face
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          # Create a .netrc file for seamless Git authentication
          echo "machine huggingface.co" > ~/.netrc
          echo "  login Dhruvk14" >> ~/.netrc
          echo "  password $HF_TOKEN" >> ~/.netrc
          chmod 600 ~/.netrc
          
          git config --global user.email "bot@github.com"
          git config --global user.name "SyncBot"
          # Check if the branch exists locally and push it to the remote
          if git ls-remote --exit-code hf main; then
            git push --force hf main
          else
            git remote add hf https://huggingface.co/spaces/Dhruvk14/Satellite_scheduler_updated
            git push --force hf main
          fi
