name: Sync to Hugging Face
on:
  push:
    branches: [main, master]
  workflow_dispatch:

jobs:
  sync-to-hub:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          lfs: true
      - name: Debug Info
        run: |
          git remote -v
          echo "Syncing to Dhruvk14/Satellite_scheduler_updated"
      - name: Push to hub
        env:
          HF_TOKEN: ${{ secrets.HF_TOKEN }}
        run: |
          git config --global user.email "bot@github.com"
          git config --global user.name "SyncBot"
          git push --force https://Dhruvk14:$HF_TOKEN@huggingface.co/spaces/Dhruvk14/Satellite_scheduler_updated main
